---
- name: Install Jenkins as a UI agent on a remote Ubuntu machine
  hosts: jenkins_ui_agent
  become: yes
  tasks:
    - name: Ensure the tests directory is copied to the remote machine
      copy:
        src: ../tests/
        dest: /home/jenkins/tests/
        mode: '0755'
        owner: jenkins
        group: jenkins

    - name: Update the package list
      apt:
        update_cache: yes

    - name: Install Java and other dependencies
      apt:
        name: 
          - openjdk-17-jre
          - fontconfig
          - gnupg
        state: present

    - name: Install LXD
      community.general.snap:
        name: lxd
        state: present

    - name: Initialize LXD
      shell: lxd init --auto

    - name: Create and configure a custom LXD image
      shell: |
        lxc launch ubuntu:24.04 robot-framework-base
        
        # Update and install necessary packages
        lxc exec robot-framework-base -- bash -c "
        apt-get update && 
        apt install -y python3 python3-venv python3-pip xvfb chromium-browser chromium-chromedriver wget unzip sudo"
        
     - name: Create a new user 'testuser' without a password inside the container
      command: >
        lxc exec robot-framework-base -- bash -c "
        adduser --disabled-password --gecos '' testuser &&
        usermod -aG sudo testuser
        "

    - name: Configure passwordless sudo for 'testuser' inside the container
      command: >
        lxc exec robot-framework-base -- bash -c "
        echo 'testuser ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/testuser
        "       
        
    - name: Create a virtual environment and install Python packages as 'testuser'
      command: >
        lxc exec robot-framework-base -- su - testuser -c "
        python3 -m pip install --upgrade pip
        python3 -m venv .venv && \
        source .venv/bin/activate && \
        python3 -m pip install robotframework robotframework-seleniumlibrary"

    - name: Verify Chromedriver installation inside the container
      command: >
        lxc exec robot-framework-base -- su - testuser -c "
        which chromedriver &&
        chromedriver --version
        "        
    - name: Create and configure a custom LXD image
      shell: |
        lxc stop robot-framework-base
        lxc publish robot-framework-base --alias robot-framework-base-image
        lxc delete robot-framework-base
      args:
        executable: /bin/bash




